### ISSUE TITLE
Carnotaurus & Dilophosaurus are nocturnal???

### ISSUE THREAD

**Issue by crakiMDH** [TimelessModdingTeam/JurassiCraft2#10]
I have seen that the Dilophosaurus and Carnotaurus are awake while all the dinosaurs are asleep. Is this intended?

**Comment by gegy1000** [comment]
Yes, Carnotaurus and Dilophosaurus are Crepuscular. They will wake up at 12:30PM and go to sleep at 4:30AM the next day.

**Comment by crakiMDH** [comment]
oh thats kinda cool... :D
