### ISSUE TITLE
Baby dinosaurs die when spawned in and the growth serum is used

### ISSUE THREAD

**Issue by crakiMDH** [TimelessModdingTeam/JurassiCraft2#12]
Whenever I spawn a baby dinosaur and I growth serum it, it starts losing health a bit after growing. /gamerule dinoMetabolism and /gamerule dinoGrowth don't change anything, and the dificulty doesn't either... Whats wrong?

**Comment by crakiMDH** [comment]
Will updating Llibrary make this stop?

**Comment by iLexiconn** [comment]
Updating LLibrary to 0.8.0 will fix the issue! :)

**Comment by crakiMDH** [comment]
But 0.8.0 is for 1.8.9

**Comment by gegy1000** [comment]
Yup.

**Comment by iLexiconn** [comment]
Update to LLibrary 0.7.2 if you're still on 1.7.10.

**Comment by crakiMDH** [comment]
But JC 2.0.0 pre release 5 is for 1.8.8 not 1.7.10 .-.

**Comment by iLexiconn** [comment]
1.8.8 mods are compatible with 1.8.9. I thought you were talking about JC1.

**Comment by crakiMDH** [comment]
Oh that makes sense... So the 1.8.8 mods that were incompatible with JC2 are compatible in 1.8.9?

**Comment by iLexiconn** [comment]
I guess so.

**Comment by crakiMDH** [comment]
Wow you responded so quickly xD. I hope the 1.8.8 are compatible... Downloading 1.8.9 right now!

**Comment by iLexiconn** [comment]
;)

**Comment by crakiMDH** [comment]
I can't launch forge 1.8.9 ;(. Is this a problem for mac users?

**Comment by iLexiconn** [comment]
Can you send me the crash log please?

**Comment by crakiMDH** [comment]
There is no crash log ;(

**Comment by iLexiconn** [comment]
What do you mean? You can't install forge?

**Comment by crakiMDH** [comment]
Yeah

**Comment by iLexiconn** [comment]
Err... Why not? Make sure you've launched vanilla 1.8.9 once before.

**Comment by crakiMDH** [comment]
oh... oh... I only launched it once... I'll launch it and try again...

**Comment by crakiMDH** [comment]
I launched 1.8.9 and it still didn't install forge...

**Comment by iLexiconn** [comment]
Do you get some kind of error? What does it do after pressing 'Install'?

**Comment by crakiMDH** [comment]
It says it can't install it when I double click forge to open the installer

**Comment by iLexiconn** [comment]
Screenshot?

**Comment by crakiMDH** [comment]
Wait NVM I installed 1.8.9 :). Good job I can grow dinosaurs now :D
