### ISSUE TITLE
Cleaning Station

### ISSUE THREAD

**Issue by crakiMDH** [TimelessModdingTeam/JurassiCraft2#13]
Whenever I clean a certain amount of fossils, I always get the skull or teeth of the creature that turned in. This means that Devonian, Jurassic, and Cretaceous fossils are not random, as the creature you get in that amount of fossils is the creature that you get till the stack finishes. This lowers the chances of getting various dinosaur species

**Comment by darthvader45** [comment]
I agree that this is a definite issue.  On other things:  Keep up the great work guys.  I will be anxiously anticipating the big announcement of a full-on release.

**Comment by gegy1000** [comment]
How the system works, is each vein of fossil you mine, will be the same dinosaur.

**Comment by darthvader45** [comment]
What will be included in the next prerelease?  Do we have a way of
obtaining Indominus Rex DNA/embryos?  Or is that further down the line?

On Mon, Jan 18, 2016 at 8:16 AM, gegy1000 <notifications@github.com> wrote:

> How the system works, is each vein of fossil you mine, will be the same
> dinosaur.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TimelessModdingTeam/JurassiCraft2/issues/13#issuecomment-172524753>
> .
>



-- 
Golden rule in Minecraft: Never dig straight down.

**Comment by gegy1000** [comment]
You can already obtain Indominus DNA

**Comment by darthvader45** [comment]
As Indominus is a hybrid, we simply combine the right kinds of DNA?  It
sounds awesome.

On Thu, Jan 21, 2016 at 12:29 AM, gegy1000 <notifications@github.com> wrote:

> You can already obtain Indominus DNA
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TimelessModdingTeam/JurassiCraft2/issues/13#issuecomment-173458583>
> .
>



-- 
Golden rule in Minecraft: Never dig straight down.

**Comment by darthvader45** [comment]
One more thing:  Add support for JEIAddons, so recipes can be displayed in
JEI

On Thu, Jan 21, 2016 at 9:32 AM, Josh Lefelhocz <alienkiller45@gmail.com>
wrote:

> As Indominus is a hybrid, we simply combine the right kinds of DNA?  It
> sounds awesome.
>
> On Thu, Jan 21, 2016 at 12:29 AM, gegy1000 <notifications@github.com>
> wrote:
>
>> You can already obtain Indominus DNA
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/TimelessModdingTeam/JurassiCraft2/issues/13#issuecomment-173458583>
>> .
>>
>
>
>
> --
> Golden rule in Minecraft: Never dig straight down.
>



-- 
Golden rule in Minecraft: Never dig straight down.
