### ISSUE TITLE
Dinos sleeping animations

### ISSUE THREAD

**Issue by crakiMDH** [TimelessModdingTeam/JurassiCraft2#15]
I've been playing for a while, and now, the Triceratops and Edmontosaurus who had sleeping animations don't have their animations anymore. Please fix this

**Comment by gegy1000** [comment]
Did they get hit during the night?

**Comment by crakiMDH** [comment]
Nope! I do /time set 16000 (the time I saw their sleep triggers) The Trike and Edmontos have the slow idle animation playing like all dinosaurs, instead of lying asleep. For some reason this has not affected the Therizinosaurus though... It's so strange
