### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by iLexiconn** [TimelessModdingTeam/JurassiCraft2#17]

**Comment by crakiMDH** [comment]
What do you mean with server crash? Cause there is no description provided

**Comment by gegy1000** [comment]
@crakiMDH It means the mod crashes on a server. (Not in the publicly released build)

**Comment by crakiMDH** [comment]
publicly released build? what build? The Pachy build? (the build that adds in JUST the Pachy)

**Comment by gegy1000** [comment]
There is no build that adds just the Pachy...
