### ISSUE TITLE
Leads Wont Attach To Dinosaurs

### ISSUE THREAD

**Issue by BLuegrass3** [TimelessModdingTeam/JurassiCraft2#18]
does anybody know why leads will not attach to the dinos, id like to be able to lead them around

PS-when will breeding be (re)added

**Comment by crakiMDH** [comment]
Actually, leads where only attachable to dinos in the 1.3/1.4 verions, but only if they were tamed... So until you can "tame" them they will be wild, and a leash won't be attachable

**Comment by gegy1000** [comment]
You can attach leashes to dinosaurs, but they have to be less than 50% grown. I will change this to depend on the size of the dinosaur.
