### ISSUE TITLE
DNA Combinator

### ISSUE THREAD

**Issue by HarveyCraft** [TimelessModdingTeam/JurassiCraft2#19]
I tried to use the DNA Combinator for combining DNA but it wont work.
I saw a user on youtube who goes by "TheCaffCast" And he combined DNA that was 45% and 7% and it worked for him. But I tried to combine DNA that  was under 100 but it didn't work. 

Please help. I used the pre release 2.0.0

**Comment by gegy1000** [comment]
Were they of the same dinosaur?

**Comment by HarveyCraft** [comment]
I figured out the problem, I wasn't using the same dinosaur, thanks, it works now!
