### ISSUE TITLE
Various Missing Models/Textures

### ISSUE THREAD

**Issue by seanamor** [TimelessModdingTeam/JurassiCraft2#20]
I am aware that the latest is a pre-release and will have bugs, this is just a report:
http://hastebin.com/onubulubeh.rb
Also appears sound and animation sequences are missing for most dinos
This occured when hitting this dino. The damage particles dont seem to go away either.
http://hastebin.com/esecisulow.vbs

http://i65.tinypic.com/2ijj1bl.jpg
http://i67.tinypic.com/2rzqpgj.jpg
http://i63.tinypic.com/kd0qph.jpg

**Comment by crakiMDH** [comment]
You could say what dinosaurs suffer of that instead of sending pictures ._____.
