### ISSUE TITLE
Baby dinosaurs newer glitch with Llibrary

### ISSUE THREAD

**Issue by crakiMDH** [TimelessModdingTeam/JurassiCraft2#22]
When I spawn in baby dinosaurs, this happens: I have tried 2: 
Dilophosaurus, keeps on trying to get somewhere, but the facility doesn't let it leave

I tried Mamenchisaurus, and it froze in the air... I couldn't kill it. It took ages to remove it... 

So the babys die when spawned in a grown bug got replaced with a bug that makes babies crap... I hope Llibrary can fix this

**Comment by gegy1000** [comment]
I'm not sure I understand the issue.

**Comment by iLexiconn** [comment]
Just downgrade llibrary for now. JC2 fixed the issue.

**Comment by crakiMDH** [comment]
So... When is JC2 releasing? Cause I need to know about the bug... And that it was fixed
