### ISSUE TITLE
Dinosaurs suffocate... sometimes... 

### ISSUE THREAD

**Issue by crakiMDH** [TimelessModdingTeam/JurassiCraft2#30]
Whenever I use JurassiCraft Pre release 4, and I leave a chunk, every dinosaur, and aquatic reptile that I used can sometimes spawn in a block and start suffocating... But its not an issue for Pterosaurs, as they are always flying.

**Comment by iLexiconn** [comment]
Can you test it with the latest pre-release please.

**Comment by gegy1000** [comment]
Cannot reproduce this in the current codebase

**Comment by crakiMDH** [comment]
I have tested it with the pre release 5. They don't spawn within the walls of their enclosures or paddocks, and they don't just go in trees...
