### ISSUE TITLE
Herding AI causes memory leak of dinosaur entity instances

### ISSUE THREAD

**Issue by gegy1000** [TimelessModdingTeam/JurassiCraft2#33]

**Comment by andrewmellinger** [comment]
Is this with or without the dinoHerding gameRule on?

**Comment by gegy1000** [comment]
Only with it on, when dinosaurs are added to the herd map, they aren't released from memory.

**Comment by crakiMDH** [comment]
gamerule of dino herding? When did this come out?

**Comment by andrewmellinger** [comment]
The dinoHerding code has been in for a while in "alpha" state.  Some of the behaviors are hard to prediuct for multi-entity code.  To try it out, set the "dinoHerding" gamerule to true.

**Comment by andrewmellinger** [comment]
Should be fixed in change 90d0264a4dde4c91fad1657617757ed6526bed50.
