### ISSUE TITLE
Animations sometimes hold or repeat forever

### ISSUE THREAD

**Issue by gegy1000** [TimelessModdingTeam/JurassiCraft2#36]

**Comment by gegy1000** [comment]
Also sometimes animate 'too much'.

**Comment by gegy1000** [comment]
Over-animating usually occurs after player death

**Comment by gegy1000** [comment]
Over-animating is fixed.

**Comment by Alex-the-666** [comment]
Well they could be singing

Sometimes you have to think about their feelings too
