### ISSUE TITLE
Tyrannosaurus Carcass still makes sounds

### ISSUE THREAD

**Issue by crakiMDH** [TimelessModdingTeam/JurassiCraft2#64]
When I killed a Tyrannosaurus to glimpse its death animation and model, I realized that its corpse still does the roaring sounds. However, the 6 other animals remain perfectly quite.

**Comment by gegy1000** [comment]
Thanks for the report, this is fixed for the next version. :)

**Comment by crakiMDH** [comment]
yay! Thanks! You mean stage 2 right? :D

**Comment by gegy1000** [comment]
Nope, 2.0.1

**Comment by crakiMDH** [comment]
Thanks for fixing the glitch! I don't like a dead rex roaring at me! Loving the new running animations for Gally, Para, and Trike BTW! And Raptor, if its new...
