### ISSUE TITLE
Paddocks signs

### ISSUE THREAD

**Issue by DariosaurioGM5** [TimelessModdingTeam/JurassiCraft2#7]
![2016-01-05_16 57 35](https://cloud.githubusercontent.com/assets/16557940/12119758/baee6772-b3cd-11e5-8e20-7939b9b203ca.png)

The paddock signs are broken. Once you put them it doesn't appear you can only see weird lines and also, in the interface the Megapiranha thing isn't there

**Comment by gegy1000** [comment]
The rendering is fixed, still need megapirnaha paddock sign.

**Comment by DariosaurioGM5** [comment]
Nice gegy!
