### ISSUE TITLE
Flying AI

### ISSUE THREAD

**Issue by DariosaurioGM5** [TimelessModdingTeam/JurassiCraft2#8]
![2016-01-05_16 56 24](https://cloud.githubusercontent.com/assets/16557940/12119736/98dda594-b3cd-11e5-8d4c-2701530f6476.png)
![2016-01-05_16 56 10](https://cloud.githubusercontent.com/assets/16557940/12119741/9d9c0652-b3cd-11e5-952b-6831172719c2.png)

When you spawn a pterosaur it's sitting, but when it starts flying it stays on the floor with a strange pose and it never takes off.

**Comment by gegy1000** [comment]
Temporarily reverted to old 'Ghast' AI.

**Comment by crakiMDH** [comment]
Ghast A.I? Aww they won't land anymore? I want my landing and flying Pterosaurs by the time stage 3 adds in Cearadactylus xD

**Comment by gegy1000** [comment]
You will, don't worry. ;)
