### ISSUE TITLE
Helicopters

### ISSUE THREAD

**Issue by crakiMDH** [TimelessModdingTeam/JurassiCraft2#9]
The helicopters have a new texture, but you can't really ride them. This is a bug, because I'm sure the heli is meant to be flied

**Comment by iLexiconn** [comment]
@jglrxavpok is already working on them :)

**Comment by jglrxavpok** [comment]
Helicopters are now able to fly correctly but still are buggy. Those bugs should have been dealt with in a week or two.

**Comment by crakiMDH** [comment]
Hey jglrxacpok... Is the helicopter flying correctly in a pre release? Or is it a feature for a next pre release?

**Comment by jglrxavpok** [comment]
It's for the next pre release. The helicopter flies kinda correctly for the
moment but it is still buggy.
